name: Sync Go devcontainer images

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync
        run: skopeo sync --src docker --dest docker mcr.microsoft.com/devcontainers/go ghcr.io/mcr-mirrors/devcontainers
